# Generated by Django 2.1.1 on 2018-10-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='main/', verbose_name='Логотип')),
                ('tagline', models.CharField(default='', max_length=750, verbose_name='Слоган')),
                ('tagline_2', models.CharField(default='', max_length=500, verbose_name='Слоган 2')),
                ('banner', models.ImageField(default='', upload_to='main/', verbose_name='Баннер')),
                ('phone_number', models.CharField(default='', max_length=20, verbose_name='Номер телефона')),
                ('address', models.CharField(default='', max_length=500, verbose_name='Адрес')),
                ('insta_link', models.URLField(default='', verbose_name='Ссылка на инстаграм')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
            },
        ),
    ]
