# Generated by Django 2.1.1 on 2018-10-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'Настройки SEO', 'verbose_name_plural': 'Настройки SEO'},
        ),
        migrations.AddField(
            model_name='seo',
            name='about_desc',
            field=models.CharField(default='', max_length=500, verbose_name='description о нас'),
        ),
        migrations.AddField(
            model_name='seo',
            name='about_title',
            field=models.CharField(default='', max_length=500, verbose_name='title о нас'),
        ),
        migrations.AddField(
            model_name='seo',
            name='beer_desc',
            field=models.CharField(default='', max_length=500, verbose_name='description тсраницы пива'),
        ),
        migrations.AddField(
            model_name='seo',
            name='beer_title',
            field=models.CharField(default='', max_length=500, verbose_name='title страницы пива'),
        ),
        migrations.AddField(
            model_name='seo',
            name='cart_desc',
            field=models.CharField(default='', max_length=500, verbose_name='description страницы корзина'),
        ),
        migrations.AddField(
            model_name='seo',
            name='cart_title',
            field=models.CharField(default='', max_length=500, verbose_name='title страницы корзина'),
        ),
        migrations.AddField(
            model_name='seo',
            name='delivery_desc',
            field=models.CharField(default='', max_length=500, verbose_name='description страницы доставки'),
        ),
        migrations.AddField(
            model_name='seo',
            name='delivery_title',
            field=models.CharField(default='', max_length=500, verbose_name='title страницы доставки'),
        ),
        migrations.AddField(
            model_name='seo',
            name='detail_desc',
            field=models.CharField(default='', max_length=500, verbose_name='description страницы товара'),
        ),
        migrations.AddField(
            model_name='seo',
            name='detail_title',
            field=models.CharField(default='', max_length=500, verbose_name='title страницы товара'),
        ),
        migrations.AddField(
            model_name='seo',
            name='index_desc',
            field=models.CharField(default='', max_length=500, verbose_name='description главной страницы'),
        ),
        migrations.AddField(
            model_name='seo',
            name='index_title',
            field=models.CharField(default='', max_length=500, verbose_name='title главной страницы'),
        ),
        migrations.AddField(
            model_name='seo',
            name='snacks_desc',
            field=models.CharField(default='', max_length=500, verbose_name='description страницы снеков'),
        ),
        migrations.AddField(
            model_name='seo',
            name='snacks_title',
            field=models.CharField(default='', max_length=500, verbose_name='title страницы снеков'),
        ),
    ]
