# Generated by Django 2.1.1 on 2018-10-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20181007_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='map',
            field=models.TextField(default='', verbose_name='Html код карты(embed)'),
        ),
    ]
