# Generated by Django 2.1.1 on 2018-10-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_siteinfo_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='logo_text1',
            field=models.CharField(default='', help_text='Верхняя строчка текста в логотипе', max_length=250, verbose_name='Текст лого 1'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='logo_text2',
            field=models.CharField(default='', help_text='Нижняя строчка текста в логотипе', max_length=250, verbose_name='Текст лого 2'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='tagline',
            field=models.CharField(default='', max_length=750, verbose_name='Заголовок(h1)'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='tagline_2',
            field=models.CharField(default='', max_length=500, verbose_name='Заголовок(h2)'),
        ),
    ]
