# Generated by Django 2.1.1 on 2018-10-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftshop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
