# Generated by Django 2.1.1 on 2018-10-07 17:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('craftshop', '0002_delete_siteinfo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='beer',
            managers=[
                ('display', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='snack',
            managers=[
                ('display', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='snack',
            old_name='packing',
            new_name='packed',
        ),
        migrations.AddField(
            model_name='beer',
            name='available',
            field=models.BooleanField(default=True, verbose_name='ОТображается на сайте'),
        ),
        migrations.AddField(
            model_name='snack',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен на сайте'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='filtering_type',
            field=models.CharField(choices=[('f', 'Фильтрованное'), ('n', 'Нефильтрованное')], default='f', max_length=200, verbose_name='Фильтрация'),
        ),
    ]
