# Generated by Django 2.1.1 on 2018-10-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftshop', '0003_auto_20181007_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='filtering_type',
            field=models.CharField(choices=[('Фильтрованоое', 'f'), ('Нефильтрованное', 'n')], default='f', max_length=200, verbose_name='Фильтрация'),
        ),
    ]
