# Generated by Django 2.1.1 on 2018-10-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftshop', '0004_auto_20181008_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='category',
        ),
        migrations.DeleteModel(
            name='SnackCategory',
        ),
    ]
