# Generated by Django 2.1.1 on 2018-10-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftshop', '0005_auto_20181011_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='filtering_type',
            field=models.CharField(default='Фильтрованное', max_length=200, verbose_name='Фильтрация'),
        ),
    ]
