# Generated by Django 2.1.1 on 2018-10-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftshop', '0006_auto_20181011_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='combos/', verbose_name='Изображение')),
                ('name', models.CharField(default='', max_length=500, verbose_name='Название')),
                ('ingredients', models.CharField(default='', max_length=1000, verbose_name='Состав')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Комбо',
                'verbose_name_plural': 'Комбо',
            },
        ),
    ]
